baseURL = "https://macbargiel.com/"
locale = "en-us"
title = "Maciej Bargiel"
enableRobotsTXT = true

[params]
  description = "Notes and writing by Maciej Bargiel."
  author = "Maciej Bargiel"

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false
  style = "github"

[taxonomies]
  tag = "tags"

[[menu.main]]
  name = "Writing"
  url = "/posts/"
  weight = 1
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

[outputs]
  home = ["HTML", "RSS"]
